name: E2E tests

on: [pull_request]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install node modules
        run: npm i

      - uses: actions/cache@v2
        with:
          path: 'ios/Pods'
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Install pods
        run: cd ios && pod install && cd ..

      - name: Install detox-cli
        run: npm install --global detox-cli

      - name: Add wix registry to brew
        run: brew tap wix/brew

      - name: Install applesimutils
        run: brew install applesimutils

      - name: Set e2e envs
        run: npm run buildenv:e2e

      - name: Build app
        run: npm run e2e:build:ios

      - name: Run tests
        run: npm run e2e:test:ios
